### ISSUE TITLE
clean("c:/temp/..") results in "c:", not "c:/"

### ISSUE THREAD

**Issue by vivainio** [danreeves/path-clean#12]
You would expect "c:/temp/.." to be normalized to "c:/", but it results in "c:". "c:" does not mean the root of windows file system, but rather current directory in drive c:.

```rust
    let buf = clean("c:/temp/..");
    assert_eq!(buf, "c:");
```

**Comment by danreeves** [comment]
fixed in [1353191](https://github.com/danreeves/path-clean/commit/1353191f317e12713e0c1471f61827e799071b9f)
