### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by Dherse** [danreeves/path-clean#14]
Hello,

There is ongoing discussion for sanitizing paths in [typst](https://github.com/typst/typst), I was wondering if you consider this implementation to be acceptable as a safety feature? For example to check whether a script is trying to access a file outside of the predetermined root directory?

Thanks in advance,

Dherse

**Comment by danreeves** [comment]
Hey,

I probably wouldn't rely on this only. From the README:
> It performs this transform lexically, without touching the filesystem. Therefore it doesn't do any symlink resolution or absolute path resolution.

The main purpose of this package is to remove duplication or redundant information from a path.

**Comment by Dherse** [comment]
Thanks a lot for the answer ;)
