### ISSUE TITLE
LICENSE-APACHE file does not contain the Apache-2.0 license

### ISSUE THREAD

**Issue by principis** [danreeves/path-clean#15]
Hi, I'm trying to package path-clean for Fedora. During the review process it was pointed out that the [LICENSE-APACHE](https://github.com/danreeves/path-clean/blob/master/LICENSE-APACHE) file only contains the header, but not the Apache-2.0 license itself, as is required.

You can get the full license from [here](https://www.apache.org/licenses/LICENSE-2.0.txt). Replacing the file would suffice. Thanks in advance!

**Comment by danreeves** [comment]
Thanks for the ticket, I've updated the file to contain the full text

**Comment by principis** [comment]
Thanks!
