### ISSUE TITLE
Consider adding #![forbid(unsafe_code)]

### ISSUE THREAD

**Issue by ssokolow** [danreeves/path-clean#8]
[cargo-geiger](https://github.com/rust-secure-code/cargo-geiger) marks crates in one of three ways:

* Red for crates using `unsafe` and, thus, in need of more careful and skilled auditing.
* Uncoloured for crates wth no `unsafe`
* Green for crates which use `#![forbid(unsafe_code)]`

Given that the point of path-clean is to "[perform] this transform lexically, without touching the filesystem" (unlike [normpath](https://lib.rs/crates/normpath) which depends on `GetFullPathNameW` on Windows), adding `#![forbid(unsafe_code)]` as an additional indicator of the intent to do it without FFI calls seems like a good idea.

**Comment by danreeves** [comment]
Added in #10
