### ISSUE TITLE
Don't assume valid UTF-8

### ISSUE THREAD

**Issue by ssokolow** [danreeves/path-clean#9]
Currently, your `clean` function requires `&str` and your trait just throws out any paths containing invalid UTF-8.

Given how easily one can have invalid UTF-8 on POSIX platforms from [mojibake](https://en.wikipedia.org/wiki/Mojibake) in filenames (eg. Load data onto a mobile device that uses latin1 on-disk using its USB Mass Storage Device mode, then pull the SD card out and plug it into a UTF-8 Linux device directly), this makes it of very limited use. (And Windows also allows unpaired UTF-16 surrogates in filenames for historical reasons.)

The proper solution would be to use the `Path::components` iterator so you don't need to convert to `&str` to match on component types or, for that matter, even think about what path separator the platform is using.

You'd just get a sequence of `Prefix(PrefixComponent)` (Stuff like `C:` or `\\server\share`), `RootDir`, `CurDir`, `ParentDir`, and `Normal(&OsStr)` values, and it'd collapse away `//`, `/./`, and trailing `/` and `/.` for you.

(That'd also allow you to eliminate an unnecessary intermediate copy in going from `PathBuf` to `&str`, since you can just `impl` your trait on `Path`.)

**Comment by danreeves** [comment]
I think this is resolved by #10
